export default {
  documentation: 'Documentation',
  'getting-started': 'Getting Started',
  'building-agents': 'Building Agents',
  'agent-examples': 'Agent Examples',
  'agents': 'Agents (Advanced)',
  'a2a': 'A2A Protocol',
  'deployment': 'Deployment',
  'contracts': 'Smart Contracts',
  'cli': 'CLI Commands',
  'moderation': 'Moderation',
  'reference': 'Technical Reference',
  'legal': 'Legal',
  about: 'About',
  // API Reference pages
  'api-reference': 'API Reference',
  authentication: 'Authentication',
  'real-time': 'Real-Time (SSE)',
  markets: 'Markets API',
  users: 'Users API',
  social: 'Social API',
  errors: 'Error Handling',
  'rest-api-reference': 'REST API Reference',
  _generated: 'Generated Docs'
}
