#!/usr/bin/env bun
/**
 * Check if trajectories are real or synthetic
 */

import { db, desc, trajectories } from '@babylon/db';

async function main() {
  console.log('Checking data source of trajectories...\n');

  const recent = await db
    .select({
      agentId: trajectories.agentId,
      scenarioId: trajectories.scenarioId,
      stepsJson: trajectories.stepsJson,
      metadataJson: trajectories.metadataJson,
    })
    .from(trajectories)
    .orderBy(desc(trajectories.createdAt))
    .limit(5);

  let syntheticCount = 0;
  let realCount = 0;

  for (const t of recent) {
    console.log('═'.repeat(60));
    console.log('Agent ID:', t.agentId);
    console.log('Scenario:', t.scenarioId);

    // Check for synthetic markers
    const isSynthetic =
      t.agentId?.includes('agent-') &&
      t.agentId?.match(/agent-\w+-\d+/) !== null &&
      t.scenarioId?.includes('multi-archetype');

    const steps = JSON.parse(t.stepsJson || '[]');
    const firstStep = steps[0];

    console.log('First action:', firstStep?.action?.actionType);

    // Check LLM calls
    const llmCalls = firstStep?.llmCalls || [];
    console.log('LLM calls in first step:', llmCalls.length);

    if (llmCalls.length > 0) {
      const firstCall = llmCalls[0];
      console.log('  Model:', firstCall?.model);
      console.log(
        '  Response preview:',
        firstCall?.response?.substring(0, 100) + '...'
      );

      // Check if response looks fake/hardcoded
      const responseIsFake =
        firstCall?.response?.includes('Looking for edge') ||
        firstCall?.response?.includes('evaluating');
      console.log(
        '  Response appears synthetic:',
        responseIsFake ? '⚠️ YES' : '✅ NO'
      );
    }

    // Check metadata for synthetic markers
    const metadata =
      typeof t.metadataJson === 'string'
        ? JSON.parse(t.metadataJson)
        : t.metadataJson || {};

    console.log('Metadata:', JSON.stringify(metadata).substring(0, 100));

    if (isSynthetic || metadata?.archetype) {
      console.log('\n⚠️  DATA SOURCE: SYNTHETIC (generated by train generate)');
      syntheticCount++;
    } else {
      console.log('\n✅ DATA SOURCE: POTENTIALLY REAL');
      realCount++;
    }
  }

  console.log('\n' + '═'.repeat(60));
  console.log('SUMMARY');
  console.log('═'.repeat(60));
  console.log(`Synthetic trajectories: ${syntheticCount}`);
  console.log(`Potentially real: ${realCount}`);

  if (syntheticCount > 0) {
    console.log('\n⚠️  WARNING: Synthetic data detected!');
    console.log(
      '   The "babylon train generate" command creates FAKE trajectories'
    );
    console.log('   with hardcoded behaviors and Math.random() decisions.');
    console.log('');
    console.log('   To generate REAL trajectories:');
    console.log('   1. Start the server: bun run dev');
    console.log(
      '   2. Run: babylon train parallel --archetypes trader --num-agents 2 --ticks 10'
    );
    console.log('   OR');
    console.log('   3. Let real agents run with recordTrajectories=true');
  }

  process.exit(0);
}

main().catch(console.error);
