/**
 * Babylon Question Manager
 * 
 * @module engine/QuestionManager
 * 
 * @description
 * Manages the complete lifecycle of prediction market questions in the Babylon game.
 * Questions are the core mechanic that drives events, NPC behavior, and player betting.
 * 
 * **Core Responsibilities:**
 * - Generate new questions daily (1-3 per day) based on scenarios and recent events
 * - Track active questions (max 20 concurrent)
 * - Resolve questions when resolution date is reached (24h-7d from creation)
 * - Generate resolution events that definitively prove outcomes
 * - Ensure game events are aligned with active questions
 * 
 * **Question Lifecycle:**
 * 1. **Creation** - Generated by LLM with resolutionDate 24h-7d in future
 * 2. **Active** - Appears in markets, events generated around it, tradable
 * 3. **Resolved** - Outcome determined, positions settled, no longer tradable
 * 4. **Cancelled** - Removed without resolution (rare, edge cases only)
 * 
 * **Generation Strategy:**
 * - Uses LLM to create contextually relevant questions
 * - Considers recent events and current storylines
 * - Avoids duplicate or overlapping questions
 * - Ensures questions align with available actors and organizations
 * 
 * **Resolution Timing:**
 * - Questions resolve 1-7 days after creation
 * - Longer timespans for complex questions (mergers, investigations)
 * - Shorter timespans for urgent developments (announcements, scandals)
 * - Resolution event generated to prove outcome definitively
 * 
 * @see {@link GameEngine} - Uses QuestionManager to generate daily questions
 * @see {@link FeedGenerator} - Creates posts and discussions about active questions
 * 
 * @example
 * ```typescript
 * const qm = new QuestionManager(llmClient);
 * 
 * // Generate new questions
 * const questions = await qm.generateDailyQuestions({
 *   currentDate: '2025-10-15',
 *   scenarios,
 *   actors,
 *   organizations,
 *   activeQuestions: [],
 *   recentEvents: [],
 *   nextQuestionId: 1
 * });
 * 
 * // Check for questions to resolve
 * const toResolve = qm.getQuestionsToResolve(activeQuestions, '2025-10-16');
 * 
 * // Resolve a question
 * const resolved = qm.resolveQuestion(question, true); // true = YES outcome
 * ```
 */

import type { Question, Scenario, SelectedActor, Organization, DayTimeline, WorldEvent } from '@/shared/types';
import type { BabylonLLMClient } from '../generator/llm/openai-client';
import { BabylonLLMClient as BabylonLLMClientValue } from '../generator/llm/openai-client';
import { questionGeneration, questionResolutionValidation, renderPrompt, generateWorldContext, worldImpactAssessment } from '@/prompts';
import { logger } from '@/lib/logger';
import { shuffleArray } from '@/lib/utils/randomization';
import { worldFactsService } from '@/lib/services/world-facts-service';
import { db, eq, gte, desc, inArray, and, worldEvents, questions, actors, organizations, trendingTags, tags, markets } from '@/db';
import { PredictionPricing } from '@/lib/prediction-pricing';
import { Decimal } from '@/db';
import { generateSnowflakeId } from '@/lib/snowflake';
import { MarketDecisionEngine } from '@/engine/MarketDecisionEngine';
import { MarketContextService } from '@/lib/services/market-context-service';
import { TradeExecutionService } from '@/lib/services/trade-execution-service';
import { ArticleGenerator, type Article } from '@/engine/ArticleGenerator';
import * as fs from 'fs';
import * as path from 'path';

/**
 * Parameters for question generation
 * 
 * @interface QuestionCreationParams
 * 
 * @property currentDate - ISO date string (YYYY-MM-DD) for the generation date
 * @property scenarios - Available game scenarios for context
 * @property actors - Available actors (filtered to main/supporting roles)
 * @property organizations - Available organizations (companies, media, etc.)
 * @property activeQuestions - Currently active questions (to avoid duplicates)
 * @property recentEvents - Recent game history for context
 * @property nextQuestionId - Next available numeric ID for new questions
 */
export interface QuestionCreationParams {
  currentDate: string;
  scenarios: Scenario[];
  actors: SelectedActor[];
  organizations: Organization[];
  activeQuestions: Question[];
  recentEvents: DayTimeline[];
  nextQuestionId: number;
}

/**
 * Question Manager - Handles question lifecycle
 * 
 * @class QuestionManager
 * 
 * @description
 * Central manager for all prediction market questions. Uses LLM to generate
 * contextually relevant questions and manages their lifecycle from creation
 * through resolution.
 * 
 * **Key Methods:**
 * - `generateDailyQuestions()` - Create 1-3 new questions per day
 * - `getQuestionsToResolve()` - Find questions ready to resolve
 * - `resolveQuestion()` - Mark question as resolved with final outcome
 * - `generateResolutionEvent()` - Create definitive proof of outcome
 * 
 * @usage
 * Instantiated once by GameEngine and used throughout the game lifecycle.
 */
export class QuestionManager {
  private llm: BabylonLLMClient;

  /**
   * Create a new QuestionManager instance
   * 
   * @param llm - Babylon LLM client for question generation
   */
  constructor(llm: BabylonLLMClient) {
    this.llm = llm;
  }

  /**
   * Generate new questions for the current day
   * 
   * @param params - Question creation parameters including context and IDs
   * @returns Array of newly generated questions (1-3 questions, empty if at capacity)
   * 
   * @description
   * Uses LLM to generate contextually relevant prediction market questions based on
   * recent events, active scenarios, and available actors. Questions are designed
   * to drive interesting events and player engagement.
   * 
   * **Generation Logic:**
   * - Generates 1-3 questions per call (random)
   * - Respects 20 question maximum (returns empty array if at capacity)
   * - Uses recent events for contextual continuity
   * - Avoids duplicating active questions
   * - Shuffles actors/orgs for variety
   * 
   * **Resolution Timing:**
   * - LLM determines `daysUntilResolution` (1-7 days)
   * - Resolution date calculated from currentDate
   * - Clamped to valid range (1-7 days)
   * 
   * **Question Properties:**
   * - `id`: Numeric ID starting from `nextQuestionId`
   * - `text`: LLM-generated question text
   * - `scenario`: Scenario ID this question relates to
   * - `outcome`: Predetermined outcome (true = YES, false = NO)
   * - `status`: Always 'active' for new questions
   * - `createdDate`: Current date
   * - `resolutionDate`: 1-7 days in the future
   * 
   * @throws Never throws - returns empty array on error
   * 
   * @example
   * ```typescript
   * const questions = await qm.generateDailyQuestions({
   *   currentDate: '2025-10-15',
   *   scenarios: gameScenarios,
   *   actors: mainActors,
   *   organizations: companies,
   *   activeQuestions: [...existingQuestions],
   *   recentEvents: [...recentDays],
   *   nextQuestionId: 42
   * });
   * // => [
   * //   { id: 42, text: "Will TechCorp announce...", outcome: true, ... },
   * //   { id: 43, text: "Will the scandal force...", outcome: false, ... }
   * // ]
   * ```
   */
  async generateDailyQuestions(params: QuestionCreationParams): Promise<Question[]> {
    const {
      currentDate,
      scenarios,
      actors,
      organizations,
      activeQuestions,
      recentEvents,
      nextQuestionId,
    } = params;

    // Don't generate if we're at max capacity (20 questions)
    if (activeQuestions.length >= 20) {
      logger.warn('Max 20 questions reached, skipping generation', undefined, 'QuestionManager');
      return [];
    }

    // Generate 1-3 new questions
    const numToGenerate = Math.min(
      Math.floor(Math.random() * 3) + 1, // 1-3 questions
      20 - activeQuestions.length // Don't exceed max
    );

    const currentDateObj = new Date(currentDate);

    // Build context from recent events
    const recentContext = recentEvents.length > 0
      ? `\n\nRECENT EVENTS (Last ${recentEvents.length} days):\n${recentEvents
          .slice(-5)
          .map(day => `Day ${day.day}: ${day.events.map(e => e.description).join('; ')}`)
          .join('\n')}`
      : '';

    // Build context from active questions
    const activeQuestionsContext = activeQuestions.length > 0
      ? `\n\nCURRENT ACTIVE QUESTIONS (${activeQuestions.length}/20):\n${activeQuestions
          .map(q => `- ${q.text} (resolves ${q.resolutionDate})`)
          .join('\n')}`
      : '\n\nNo active questions yet.';

    const prompt = await this.buildQuestionGenerationPrompt(
      scenarios,
      actors,
      organizations,
      recentContext,
      activeQuestionsContext,
      numToGenerate
    );

    const rawResponse = await this.llm.generateJSON<{
      questions: Array<{
        text: string;
        scenario: number;
        daysUntilResolution: number; // 1-7 days
        expectedOutcome: boolean;
      }>;
    } | {
      response: {
        questions: Array<{
          text: string;
          scenario: number;
          daysUntilResolution: number; // 1-7 days
          expectedOutcome: boolean;
        }>;
      }
    }>(prompt, undefined, {
      temperature: 0.9,
      maxTokens: 8000,
      promptType: 'question_generate_batch',
    });

    // Handle XML structure
    const response = 'response' in rawResponse && rawResponse.response
      ? rawResponse.response
      : rawResponse as { questions: Array<{ text: string; scenario: number; daysUntilResolution: number; expectedOutcome: boolean }> };

    if (!response.questions || response.questions.length === 0) {
      logger.warn('LLM returned no questions', undefined, 'QuestionManager');
      return [];
    }

    // Convert to Question objects with dates and IDs
    const questions: Question[] = response.questions.slice(0, numToGenerate).map((q, index) => {
      const resolutionDate = new Date(currentDateObj);
      resolutionDate.setDate(
        resolutionDate.getDate() + Math.max(1, Math.min(7, q.daysUntilResolution || 3))
      );

      return {
        id: nextQuestionId + index,
        text: q.text,
        scenario: q.scenario || 1,
        outcome: q.expectedOutcome,
        rank: 1,
        createdDate: currentDate,
        resolutionDate: resolutionDate.toISOString().split('T')[0]!,
        status: 'active',
      };
    });

    return questions;
  }

  /**
   * Build LLM prompt for question generation
   */
  private async buildQuestionGenerationPrompt(
    scenarios: Scenario[],
    actors: SelectedActor[],
    organizations: Organization[],
    recentContext: string,
    activeQuestionsContext: string,
    numToGenerate: number
  ): Promise<string> {
    const scenariosList = scenarios
      .map(
        s => `
Scenario ${s.id}: ${s.title}
${s.description}
Actors: ${s.mainActors.join(', ')}
${s.involvedOrganizations?.length ? `Organizations: ${s.involvedOrganizations.join(', ')}` : ''}
`
      )
      .join('\n');

    // Shuffle actors and organizations to add variety to prompts
    const shuffledActors = shuffleArray(
      actors.filter(a => a.role === 'main' || a.role === 'supporting')
    );
    const actorsList = shuffledActors
      .slice(0, 20)
      .map(a => `- ${a.name}: ${a.description}`)
      .join('\n');

    const shuffledOrgs = shuffleArray(
      organizations.filter(o => o.type === 'company')
    );
    const orgsList = shuffledOrgs
      .slice(0, 15)
      .map(o => `- ${o.name}: ${o.description}`)
      .join('\n');

    // Generate world context with reality grounding for better question quality
    const worldContext = await generateWorldContext({
      maxActors: 50,
      realityGroundingLevel: 'concise',
    });

    // Load example questions
    let exampleQuestions = '';
    try {
      const examplesPath = path.join(process.cwd(), 'data', 'question-examples.md');
      if (fs.existsSync(examplesPath)) {
        const content = fs.readFileSync(examplesPath, 'utf-8');
        const lines = content.split('\n').filter(line => line.trim().length > 0);
        const shuffled = shuffleArray(lines);
        exampleQuestions = shuffled.slice(0, 10).map(q => `✅ "${q}"`).join('\n');
      }
    } catch (error) {
      logger.warn('Failed to load question examples', { error }, 'QuestionManager');
    }

    return renderPrompt(questionGeneration, {
      scenariosList,
      actorsList,
      orgsList,
      recentContext,
      activeQuestionsContext,
      numToGenerate: numToGenerate.toString(),
      exampleQuestions,
      ...worldContext,
    });
  }

  /**
   * Get questions that should be resolved today
   * 
   * @param activeQuestions - Array of currently active questions
   * @param currentDate - Current date as ISO string (YYYY-MM-DD)
   * @returns Array of questions ready for resolution
   * 
   * @description
   * Filters active questions to find those whose resolution date has been reached.
   * These questions should be resolved in the current game tick.
   * 
   * **Resolution Criteria:**
   * - Question must have a `resolutionDate` set
   * - Resolution date must be <= current date
   * - Only checks active questions (not already resolved)
   * 
   * **Typical Flow:**
   * 1. GameEngine calls this during tick
   * 2. For each returned question:
   *    - Generate resolution event
   *    - Call `resolveQuestion()`
   *    - Settle all positions
   *    - Update reputation
   * 
   * @usage
   * Called by GameEngine every tick to check for questions ready to resolve.
   * 
   * @example
   * ```typescript
   * const toResolve = qm.getQuestionsToResolve(activeQuestions, '2025-10-20');
   * // => [Question { id: 5, resolutionDate: '2025-10-19', ... }]
   * 
   * for (const question of toResolve) {
   *   // Generate resolution event
   *   // Resolve question
   *   // Settle positions
   * }
   * ```
   */
  getQuestionsToResolve(activeQuestions: Question[], currentDate: string): Question[] {
    const currentDateObj = new Date(currentDate);

    return activeQuestions.filter(q => {
      if (!q.resolutionDate) return false;
      const resolutionDateObj = new Date(q.resolutionDate);
      return resolutionDateObj <= currentDateObj;
    });
  }

  /**
   * Resolve a question with final outcome
   * 
   * @param question - Question to resolve
   * @param outcome - Final outcome (true = YES, false = NO)
   * @returns Resolved question with updated status and outcome
   * 
   * @description
   * Marks a question as resolved and records the final outcome. This is a pure
   * function that returns a new question object - it does not mutate the input.
   * 
   * **What This Does:**
   * - Sets `status` to 'resolved'
   * - Sets `resolvedOutcome` to the provided outcome
   * - Preserves all other question properties
   * 
   * **What This Does NOT Do:**
   * - Does not settle positions (handled by GameEngine)
   * - Does not update reputation (handled by ReputationService)
   * - Does not persist to database (handled by GameEngine)
   * - Does not generate events (handled by GameEngine)
   * 
   * @usage
   * Called by GameEngine after generating a resolution event.
   * 
   * @example
   * ```typescript
   * const question = { id: 5, text: "Will...", outcome: true, status: 'active', ... };
   * const resolved = qm.resolveQuestion(question, true);
   * // => { ...question, status: 'resolved', resolvedOutcome: true }
   * ```
   */
  resolveQuestion(question: Question, outcome: boolean, resolutionDescription?: string, resolutionProofUrl?: string): Question {
    return {
      ...question,
      status: 'resolved',
      resolvedOutcome: outcome,
      resolutionDescription,
      resolutionProofUrl,
    };
  }

  /**
   * Generate proof content (Article) for a resolved question
   */
  async generateProofContent(
    question: Question,
    eventDescription: string,
    actors: SelectedActor[],
    organizations: Organization[]
  ): Promise<{ type: 'article'; article: Article; url: string } | null> {
      const articleGenerator = new ArticleGenerator(this.llm);
      
      // Find a suitable media organization
      const mediaOrgs = organizations.filter(o => o.type === 'media');
      // Use random media org or fallback to first org
      const org = mediaOrgs.length > 0 
        ? mediaOrgs[Math.floor(Math.random() * mediaOrgs.length)] 
        : organizations[0];
      
      if (!org) return null;

      // Create a synthetic event for the article generator
      const event: WorldEvent = {
          id: `resolution-${question.id}`,
          day: 0, // Placeholder, not critical for article generation logic here
          type: 'revelation',
          description: eventDescription,
          actors: [],
          relatedQuestion: typeof question.id === 'number' ? question.id : undefined,
          pointsToward: question.outcome ? 'YES' : 'NO',
          visibility: 'public'
      };

      try {
        const article = await articleGenerator.generateArticleForQuestion(
            question,
            org,
            'resolution',
            actors,
            [event]
        );

        return { 
            type: 'article', 
            article,
            url: `/article/${article.id}`
        };
      } catch (error) {
          logger.error('Failed to generate proof article', { error }, 'QuestionManager');
          return null;
      }
  }

  /**
   * Generate resolution event and proof content
   */
  async generateResolutionWithProof(
    question: Question,
    actors: SelectedActor[],
    organizations: Organization[],
    recentEvents: DayTimeline[]
  ): Promise<{ description: string; proof?: { type: 'article'; article: Article; url: string } }> {
      const description = await this.generateResolutionEvent(question, actors, organizations, recentEvents);
      
      // Generate proof
      const proof = await this.generateProofContent(question, description, actors, organizations);
      
      return { description, proof: proof || undefined };
  }

  /**
   * Generate a resolution event that proves the question outcome
   * 
   * @param question - Question being resolved
   * @param _actors - Available actors (currently unused, kept for interface compatibility)
   * @param _organizations - Available organizations (currently unused, kept for interface compatibility)
   * @param recentEvents - Recent game timeline for context
   * @returns Event description string that definitively proves the outcome
   * 
   * @description
   * Uses LLM to generate a dramatic, definitive event that proves whether the
   * question outcome is YES or NO. This event provides closure to the narrative
   * and justifies position settlements.
   * 
   * **Event Requirements:**
   * - Must be concrete and observable
   * - Must DEFINITIVELY prove the outcome
   * - Should reference recent related events for continuity
   * - Should be dramatic and satisfying for players
   * 
   * **LLM Prompting:**
   * - Uses recent related events as context
   * - Instructs LLM to prove specific outcome (YES/NO)
   * - Temperature 0.7 for consistent but varied events
   * - Falls back to template if LLM fails
   * 
   * @usage
   * Called by GameEngine when resolving questions.
   * 
   * @example
   * ```typescript
   * const event = await qm.generateResolutionEvent(
   *   question,
   *   actors,
   *   organizations,
   *   recentTimeline
   * );
   * // => "TechCorp officially announces merger completion, signing ceremony held today"
   * ```
   */
  async generateResolutionEvent(
    question: Question,
    _actors: SelectedActor[],
    _organizations: Organization[],
    recentEvents: DayTimeline[]
  ): Promise<string> {
    // Get context from recent events related to this question
    const relatedEvents = recentEvents
      .flatMap(day => day.events)
      .filter(e => e.relatedQuestion === question.id)
      .slice(-3);

    const eventHistory =
      relatedEvents.length > 0
        ? `Recent events: ${relatedEvents.map(e => e.description).join('; ')}`
        : 'No prior events';

    const outcomeContext = question.outcome 
      ? 'PROVES it happened/succeeded' 
      : 'PROVES it failed/was cancelled/did not happen';

    const prompt = renderPrompt(questionResolutionValidation, {
      questionText: question.text,
      outcome: question.outcome ? 'YES' : 'NO',
      eventHistory,
      contextInfo: '',
      outcomeContext
    });

    const rawResponse = await this.llm.generateJSON<{ event: string; type: string } | { response: { event: string; type: string } }>(
      prompt,
      undefined,
      { temperature: 0.7, maxTokens: 5000, promptType: 'question_resolution_event' }
    );

    // Handle XML structure
    const response = 'response' in rawResponse && rawResponse.response
      ? rawResponse.response
      : rawResponse as { event: string; type: string };

    const eventDescription = response.event || `Resolution: ${question.text} outcome is ${question.outcome ? 'YES' : 'NO'}`;

    // Assess world impact
    await this.assessAndRecordWorldImpact(question, eventDescription);

    return eventDescription;
  }

  /**
   * Assess if a resolution event changes the world and record it if so
   */
  private async assessAndRecordWorldImpact(
    question: Question,
    resolutionEvent: string
  ): Promise<void> {
    try {
      const worldContext = await generateWorldContext({
        includeWorldFacts: true,
        realityGroundingLevel: 'concise'
      });

      const prompt = renderPrompt(worldImpactAssessment, {
        worldFacts: worldContext.worldFacts,
        questionText: question.text,
        outcome: question.outcome ? 'YES' : 'NO',
        outcomeText: question.outcome ? 'True/Happened' : 'False/Did not happen',
        resolutionEvent,
      });

      const response = await this.llm.generateJSON<{
        changesWorld: boolean;
        newFact: string | null;
      } | {
        response: {
          changesWorld: boolean;
          newFact: string | null;
        }
      }>(prompt, undefined, { promptType: 'question_assess_world_impact' });

      // Handle potential wrapped response
      let result: { changesWorld: boolean; newFact: string | null };
      if ('response' in response) {
        result = response.response;
      } else {
        result = response;
      }

      if (result.changesWorld && result.newFact) {
        await worldFactsService.addDynamicFact(result.newFact);
        logger.info(`Added new world fact: ${result.newFact}`, { questionId: question.id }, 'QuestionManager');
      }
    } catch (error) {
      logger.error('Failed to assess world impact', { error }, 'QuestionManager');
    }
  }

  /**
   * Get all active questions from a question array
   * 
   * @param questions - Array of questions to filter
   * @returns Array of questions with status='active'
   * 
   * @description
   * Simple filter utility to extract active questions. Active questions are
   * those that are currently tradable and generating events.
   * 
   * @usage
   * Used by GameEngine to get questions for event generation.
   * 
   * @example
   * ```typescript
   * const active = qm.getActiveQuestions(allQuestions);
   * // => [Question { status: 'active', ... }, Question { status: 'active', ... }]
   * ```
   */
  getActiveQuestions(questions: Question[]): Question[] {
    return questions.filter(q => q.status === 'active');
  }

  /**
   * Get all resolved questions from a question array
   * 
   * @param questions - Array of questions to filter
   * @returns Array of questions with status='resolved'
   * 
   * @description
   * Simple filter utility to extract resolved questions. Useful for analytics,
   * displaying history, and calculating statistics.
   * 
   * @usage
   * Used for displaying question history and analytics.
   * 
   * @example
   * ```typescript
   * const resolved = qm.getResolvedQuestions(allQuestions);
   * // => [Question { status: 'resolved', resolvedOutcome: true, ... }]
   * ```
   */
  getResolvedQuestions(questions: Question[]): Question[] {
    return questions.filter(q => q.status === 'resolved');
  }

  /**
   * Calculate days remaining until question resolves
   * 
   * @param question - Question to check
   * @param currentDate - Current date as ISO string (YYYY-MM-DD)
   * @returns Number of days until resolution (0 if today/past, 999 if no resolution date)
   * 
   * @description
   * Calculates the number of days from currentDate until the question's
   * resolutionDate. Used for urgency calculations and UI display.
   * 
   * **Return Values:**
   * - `0`: Resolves today or already past
   * - `1-7`: Days remaining (normal range)
   * - `999`: No resolution date set (shouldn't happen)
   * 
   * **Rounding:**
   * - Uses `Math.ceil()` to round up partial days
   * - Uses `Math.max(0)` to prevent negative values
   * 
   * @usage
   * Used by FeedGenerator to adjust clue strength (closer = stronger clues).
   * 
   * @example
   * ```typescript
   * const days = qm.getDaysUntilResolution(question, '2025-10-15');
   * // If resolutionDate is '2025-10-18':
   * // => 3
   * 
   * const days = qm.getDaysUntilResolution(question, '2025-10-18');
   * // If resolutionDate is '2025-10-18':
   * // => 0 (resolves today)
   * ```
   */
  getDaysUntilResolution(question: Question, currentDate: string): number {
    if (!question.resolutionDate) return 999;

    const current = new Date(currentDate);
    const resolution = new Date(question.resolutionDate);
    const diffTime = resolution.getTime() - current.getTime();
    const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

    return Math.max(0, diffDays);
  }

  /**
   * Generate questions for continuous game mode with full context
   * 
   * @param count - Number of questions to generate
   * @param deadlineMs - Deadline timestamp to abort if exceeded
   * @returns Number of questions successfully created
   * 
   * @description
   * Generates questions with complete game context including:
   * - World facts and reality grounding
   * - Recent events (last 7 days)
   * - Active and resolved questions
   * - Actors and organizations
   * - Trending topics
   * - Current markets and trades
   * 
   * Also creates markets and triggers NPC betting on new questions.
   */
  async generateQuestionsForContinuousGame(
    count: number,
    deadlineMs: number
  ): Promise<number> {
    let questionsCreated = 0;

    // Gather ALL context needed for intelligent question generation
    logger.info('Gathering context for question generation...', { count }, 'QuestionManager');
    
    const [
      worldFactsContext,
      worldContext,
      recentEvents,
      activeQuestions,
      resolvedQuestions,
      actorsList,
      organizationsList,
      trendingTagsList,
    ] = await Promise.all([
      worldFactsService.generatePromptContext(),
      generateWorldContext({ 
        maxActors: 50, 
        realityGroundingLevel: 'concise',
        includeMarkets: true,
        includePredictions: true,
        includeTrades: true,
        includeWorldFacts: true,
      }),
      // Get recent events from last 7 days
      db
        .select()
        .from(worldEvents)
        .where(
          and(
            gte(worldEvents.timestamp, new Date(Date.now() - 7 * 24 * 60 * 60 * 1000)),
            eq(worldEvents.visibility, 'public')
          )
        )
        .orderBy(desc(worldEvents.timestamp))
        .limit(20),
      // Get active questions
      db
        .select()
        .from(questions)
        .where(eq(questions.status, 'active'))
        .orderBy(desc(questions.createdAt))
        .limit(20),
      // Get recently resolved questions (last 7 days) with outcomes
      db
        .select({
          text: questions.text,
          resolvedOutcome: questions.resolvedOutcome,
          resolutionDate: questions.resolutionDate,
        })
        .from(questions)
        .where(
          and(
            eq(questions.status, 'resolved'),
            gte(questions.updatedAt, new Date(Date.now() - 7 * 24 * 60 * 60 * 1000))
          )
        )
        .orderBy(desc(questions.updatedAt))
        .limit(10),
      // Get actors (main and supporting roles)
      db
        .select({
          id: actors.id,
          name: actors.name,
          description: actors.description,
          domain: actors.domain,
          role: actors.role,
          personality: actors.personality,
          affiliations: actors.affiliations,
        })
        .from(actors)
        .where(inArray(actors.role, ['main', 'supporting']))
        .limit(30),
      // Get organizations (companies)
      db
        .select({
          id: organizations.id,
          name: organizations.name,
          description: organizations.description,
          type: organizations.type,
        })
        .from(organizations)
        .where(eq(organizations.type, 'company'))
        .limit(20),
      // Get trending topics for context (with manual join for tags)
      db
        .select({
          id: trendingTags.id,
          tagId: trendingTags.tagId,
          score: trendingTags.score,
          tagName: tags.name,
          tagDisplayName: tags.displayName,
          tagCategory: tags.category,
        })
        .from(trendingTags)
        .leftJoin(tags, eq(trendingTags.tagId, tags.id))
        .orderBy(desc(trendingTags.score))
        .limit(10),
    ]);

    // Load example questions
    let exampleQuestions = '';
    try {
      const examplesPath = path.join(process.cwd(), 'data', 'question-examples.md');
      if (fs.existsSync(examplesPath)) {
        const content = fs.readFileSync(examplesPath, 'utf-8');
        const lines = content.split('\n').filter(line => line.trim().length > 0);
        const shuffled = shuffleArray(lines);
        exampleQuestions = shuffled.slice(0, 10).map(q => `✅ "${q}"`).join('\n');
      }
    } catch (error) {
      logger.warn('Failed to load question examples', { error }, 'QuestionManager');
    }

    // Format context strings - compact format
    const recentEventsContext = recentEvents.length > 0
      ? `EVENTS(7d): ${recentEvents.slice(0, 10).map(e => `${e.description.substring(0, 60)}`).join(' | ')}`
      : '';

    const activeQuestionsContext = activeQuestions.length > 0
      ? `ACTIVE(${activeQuestions.length}): ${activeQuestions.slice(0, 10).map(q => `"${q.text.substring(0, 50)}..."`).join(' | ')}`
      : '';

    const resolvedQuestionsContext = resolvedQuestions.length > 0
      ? `RESOLVED(7d): ${resolvedQuestions.slice(0, 5).map(q => `"${q.text.substring(0, 40)}..."→${q.resolvedOutcome ? 'YES' : 'NO'}`).join(' | ')}`
      : '';

    const actorsContext = actorsList.length > 0
      ? `ACTORS: ${actorsList.slice(0, 15).map(a => a.name).join(', ')}`
      : '';

    const orgsContext = organizationsList.length > 0
      ? `COMPANIES: ${organizationsList.slice(0, 10).map(o => o.name).join(', ')}`
      : '';

    const trendingContext = trendingTagsList.length > 0
      ? `TRENDING: ${trendingTagsList.slice(0, 5).map(tt => tt.tagDisplayName || tt.tagName || 'Unknown').join(', ')}`
      : '';

    // Build compact prompt
    const contextParts = [
      worldFactsContext,
      worldContext.realityGrounding || '',
      recentEventsContext,
      activeQuestionsContext,
      resolvedQuestionsContext,
      actorsContext,
      orgsContext,
      trendingContext,
      worldContext.currentMarkets ? `MARKETS: ${worldContext.currentMarkets}` : '',
      worldContext.activePredictions ? `PREDICTIONS: ${worldContext.activePredictions}` : '',
      worldContext.recentTrades ? `TRADES: ${worldContext.recentTrades}` : '',
      exampleQuestions ? `EXAMPLES: ${exampleQuestions}` : '',
    ].filter(Boolean).join('\n');

    const prompt = `Generate ${count} prediction market questions.

${contextParts}

RULES:
- Use EXACT parody names from lists (AIlon Musk, Sam AIltman, Mark Zuckerborg)
- YES/NO only, specific & measurable, future events, publicly verifiable
- NO resignations/acquisitions/relationship-breaking
- Resolution: 1-7 days (1-2d=fast, 3-5d=medium, 6-7d=slow)
- Don't duplicate active questions

BAD: "Will X be happy?" (vague), "Will X secretly..." (unverifiable)

XML: <response><questions><question><text>...</text><resolutionCriteria>...</resolutionCriteria><daysUntilResolution>3</daysUntilResolution><expectedOutcome>yes</expectedOutcome></question></questions></response>`;

    // Generate questions in batch
    let response: {
      questions: Array<{
        text: string;
        resolutionCriteria: string;
        daysUntilResolution: number;
        expectedOutcome: string; // "yes" or "no"
      }>;
    } | {
      response: {
        questions: Array<{
          text: string;
          resolutionCriteria: string;
          daysUntilResolution: number;
          expectedOutcome: string;
        }>;
      };
    } | null = null;

    try {
      if (Date.now() > deadlineMs) {
        logger.warn('Question generation aborted due to tick budget limit', { questionsCreated }, 'QuestionManager');
        return questionsCreated;
      }

      response = await this.llm.generateJSON<{
        questions: Array<{
          text: string;
          resolutionCriteria: string;
          daysUntilResolution: number;
          expectedOutcome: string;
        }>;
      } | {
        response: {
          questions: Array<{
            text: string;
            resolutionCriteria: string;
            daysUntilResolution: number;
            expectedOutcome: string;
          }>;
        };
      }>(
        prompt,
        {
          properties: {
            questions: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  text: { type: 'string' },
                  resolutionCriteria: { type: 'string' },
                  daysUntilResolution: { type: 'number' },
                  expectedOutcome: { type: 'string' },
                },
              },
            },
          },
          required: ['questions'],
        },
        {
          temperature: 0.9,
          maxTokens: 8000,
          ...(this.llm.getProvider() === 'wandb' ? { model: 'moonshotai/kimi-k2-instruct-0905' } : {}),
          format: 'xml',
          promptType: 'question_generate_real_world',
        }
      );

      // Handle XML structure
      const questionsData = response && 'response' in response && response.response
        ? (response.response as { questions: Array<{ text: string; resolutionCriteria: string; daysUntilResolution: number; expectedOutcome: string }> }).questions
        : (response as { questions: Array<{ text: string; resolutionCriteria: string; daysUntilResolution: number; expectedOutcome: string }> }).questions;

      if (!questionsData || !Array.isArray(questionsData) || questionsData.length === 0) {
        logger.warn('No questions generated from LLM response', { response }, 'QuestionManager');
        return questionsCreated;
      }

      // Get next question number
      const [lastQuestion] = await db
        .select({ questionNumber: questions.questionNumber })
        .from(questions)
        .orderBy(desc(questions.questionNumber))
        .limit(1);
      let nextQuestionNumber = (lastQuestion?.questionNumber ?? 0) + 1;

      const scenarioId = 1; // Note: Will be replaced with dynamic scenario selection when schema supports it
      const now = new Date();

      // Create each question
      for (const questionData of questionsData.slice(0, count)) {
        if (Date.now() > deadlineMs) {
          logger.warn('Question generation aborted due to tick budget limit', { questionsCreated }, 'QuestionManager');
          break;
        }

        if (!questionData.text || !questionData.resolutionCriteria) {
          logger.warn('Invalid question data, skipping', { questionData }, 'QuestionManager');
          continue;
        }

        // Convert "yes"/"no" to boolean
        const expectedOutcomeStr = String(questionData.expectedOutcome || '').toLowerCase().trim();
        const expectedOutcome = expectedOutcomeStr === 'yes' || expectedOutcomeStr === 'true';

        // Clamp daysUntilResolution to 1-7 range and ensure it's a valid integer
        const rawDays = questionData.daysUntilResolution;
        const daysUntilResolution = Math.max(1, Math.min(7, Math.round(rawDays || 3)));

        // Calculate resolution date from current date + daysUntilResolution
        const resolutionDate = new Date();
        resolutionDate.setDate(resolutionDate.getDate() + daysUntilResolution);
        resolutionDate.setHours(23, 59, 59, 999); // Set to end of day for consistency

        logger.info(`Creating question with ${daysUntilResolution} day resolution period`, {
          questionText: questionData.text,
          daysUntilResolution,
          resolutionDate: resolutionDate.toISOString(),
          rawDaysFromLLM: rawDays,
          expectedOutcome: expectedOutcomeStr,
          outcomeBoolean: expectedOutcome,
        }, 'QuestionManager');

        const questionResults = await db
          .insert(questions)
          .values({
            id: await generateSnowflakeId(),
            questionNumber: nextQuestionNumber++,
            text: questionData.text,
            scenarioId,
            outcome: expectedOutcome,
            rank: 1,
            resolutionDate,
            status: 'active',
            updatedAt: now,
          })
          .returning();
        const question = questionResults[0]!;

        // Initialize market with sufficient liquidity for trading
        const initialLiquidity = 20000;
        const { yesShares, noShares } = PredictionPricing.initializeMarket(initialLiquidity);

        const marketResults = await db
          .insert(markets)
          .values({
            id: question.id,
            question: questionData.text,
            description: questionData.resolutionCriteria,
            yesShares: new Decimal(yesShares).toString(),
            noShares: new Decimal(noShares).toString(),
            liquidity: new Decimal(initialLiquidity).toString(),
            endDate: resolutionDate, // Same resolutionDate as question (1-7 days from now)
            gameId: 'continuous',
            updatedAt: now,
          })
          .returning();
        const market = marketResults[0]!;

        logger.debug('Question and market created with matching resolution dates', {
          questionId: question.id,
          questionNumber: question.questionNumber,
          resolutionDate: resolutionDate.toISOString(),
          daysUntilResolution,
          marketEndDate: market.endDate.toISOString(),
        }, 'QuestionManager');

        // Create market on-chain if it doesn't have onChainMarketId
        if (!market.onChainMarketId) {
          const { ensureMarketOnChain } = await import('@/lib/services/onchain-market-service');
          await ensureMarketOnChain(market.id).catch((error) => {
            logger.warn('Failed to create market on-chain (non-blocking)', { error, marketId: market.id }, 'QuestionManager');
          });
        }

        // Trigger NPC betting on this new question
        try {
          const contextService = new MarketContextService();
          
          // Create LLM client for market decisions (same as used in main tick)
          let marketDecisionLLM: BabylonLLMClient;
          if (process.env.GROQ_API_KEY) {
            marketDecisionLLM = BabylonLLMClientValue.forGroq();
          } else if (process.env.ANTHROPIC_API_KEY) {
            marketDecisionLLM = BabylonLLMClientValue.forClaude();
          } else if (process.env.OPENAI_API_KEY) {
            marketDecisionLLM = BabylonLLMClientValue.forOpenAI();
          } else {
            logger.warn('No API key for market decisions - skipping NPC betting on new question', { questionId: question.id }, 'QuestionManager');
            questionsCreated++;
            continue;
          }

          const modelName = process.env.MARKET_DECISION_MODEL || 'qwen/qwen3-32b';
          const isKimiModel = modelName.toLowerCase().includes('kimi');
          const defaultMaxOutput = isKimiModel ? 16000 : 32000;
          const maxOutputTokens = parseInt(
            process.env.MARKET_DECISION_MAX_OUTPUT_TOKENS || defaultMaxOutput.toString(),
            10
          );

          const decisionEngine = new MarketDecisionEngine(marketDecisionLLM, contextService, {
            model: modelName,
            maxOutputTokens,
          });

          // Generate decisions for NPCs - they will see the new question in context
          const decisions = await decisionEngine.generateBatchDecisions();
          
          // Filter to decisions for this new question
          const questionDecisions = decisions.filter(d => 
            d.marketType === 'prediction' && d.marketId === question.id
          );

          if (questionDecisions.length > 0) {
            const executionService = new TradeExecutionService();
            const executionResult = await executionService.executeDecisionBatch(questionDecisions);
            
            logger.info(`NPC betting on new question Q${question.questionNumber}`, {
              questionId: question.id,
              questionText: question.text,
              decisionsGenerated: questionDecisions.length,
              successfulTrades: executionResult.successfulTrades,
              failedTrades: executionResult.failedTrades,
            }, 'QuestionManager');
          }
        } catch (error) {
          logger.warn('Failed to trigger NPC betting on new question (non-blocking)', {
            error: error instanceof Error ? error.message : String(error),
            questionId: question.id,
          }, 'QuestionManager');
          // Continue even if NPC betting fails
        }

        questionsCreated++;
      }
    } catch (error) {
      logger.error(
        'Failed to generate new questions via LLM',
        { error: error instanceof Error ? error.message : String(error) },
        'QuestionManager'
      );
    }

    return questionsCreated;
  }
}
